import urllib.request, re
html = urllib.request.urlopen('http://127.0.0.1:8200/').read().decode('utf-8')
print('HTTP 200, bytes:', len(html))
i1 = html.find('/static/icons.js')
i2 = html.find('/static/nav.js')
print('icons.js before nav.js  :', i1>=0 and i1<i2)
print('icons.js at / nav.js at :', i1, i2)
print('data-lucide spans       :', html.count('data-lucide='))
print('icons used              :', sorted(set(re.findall(r'data-lucide="(\w[\w-]*)"', html))))
print('no emoji in HTML        :', not any(c in html for c in ['🎓','📚','🤖','⚙','💬','🚀','📝','📖']))
print('no handcrafted SVG paths:', 'viewBox=\"0 0 24 24\"' not in html)
print('has graduation-cap svg  :', 'M22 10v6' in html)
print('favicon has graduation  :', 'fill:#3B82F6' in html)
print('Lucide icons.js loaded  :', 'LUCIDE_ICONS' in urllib.request.urlopen('http://127.0.0.1:8200/static/icons.js').read().decode('utf-8'))
