# -*- coding: utf-8 -*-
"""Verify the rebuilt site matches requirements."""
import pathlib, re
base = pathlib.Path(r'D:\codex/content-engine/site/_site')
index_html = (base / 'index.html').read_text('utf-8')
ai_html = (base / 'ai/article/gpt-5-vs-gpt-4o-comparison.html').read_text('utf-8')
ielts_html = (base / 'exam/article/ielts-writing-band-7-strategy.html').read_text('utf-8')
def body_of(html):
    s = html.find('<div class="article-body">')
    e = html.find('</article>')
    return html[s:e] if s >= 0 and e >= 0 else ''
ai_body = body_of(ai_html)
ielts_body = body_of(ielts_html)
print('=== Site verification ===')
print('1. CET-4 / CET-6 tabs removed:', 'CET-4' not in index_html and 'CET-6' not in index_html)
print('2. New SVG logo present     :', 'logo.svg' in index_html)
print('3. Bookmark (card-star) gone:', 'card-star' not in index_html)
print('4. Exam tabs order          :', end=' ')
m = re.search(r'data-tabs="exam">(.*?)</div>', index_html, re.S)
if m:
    tabs = re.findall(r'val="([^"]+)"', m.group(1))
    print(tabs)
print('5. Table tags gone (AI body):', all(t not in ai_body for t in ['<table','<td','<th']))
print('6. Table tags gone (IELTS body):', all(t not in ielts_body for t in ['<table','<td','<th']))
print('7. Heading tags in AI body  :', sum(ai_body.count(f'<h{i}') for i in range(1,7)))
print('8. Heading tags in IELTS body:', sum(ielts_body.count(f'<h{i}') for i in range(1,7)))
print('9. Line-start bullets (AI body) :', sum(1 for l in ai_body.split('\n') if l.strip().startswith('- ') and not l.strip().startswith('---')))
print('10. Line-start bullets (IELTS body):', sum(1 for l in ielts_body.split('\n') if l.strip().startswith('- ') and not l.strip().startswith('---')))
print('11. Numbered list markers (AI) :', len(re.findall(r'<p>\d+[\.\)]\s', ai_body)))
print('12. Numbered list markers (IELTS):', len(re.findall(r'<p>\d+[\.\)]\s', ielts_body)))
print('13. <ul>/<li> in AI body     :', ai_body.count('<ul') + ai_body.count('<li'))
print('14. <ul>/<li> in IELTS body  :', ielts_body.count('<ul') + ielts_body.count('<li'))
print('15. Flagged emoji 🎓 in article body:', '🎓' not in ai_body and '🎓' not in ielts_body)
print('16. Flagged emoji 🤖 in article body:', '🤖' not in ai_body and '🤖' not in ielts_body)
print('17. Flagged entity &#127891; in article body:', '&#127891;' not in ai_body and '&#127891;' not in ielts_body)
print('18. Flagged entity &#129302; in article body:', '&#129302;' not in ai_body and '&#129302;' not in ielts_body)
print()
print('=== AI body sample ===')
print(ai_body[:400])
print()
print('=== IELTS body sample ===')
print(ielts_body[:400])
